# Site Settings
title:               Theorie der Prosa
tagline:             Uni Basel
description:
baseurl:            "/Lagrange"
url:                #"https://not-balb.github.io"
github:
  url:               #"https://not-balb.github.io/Lagrange"
author:
  name:              "Jodok Trösch"
  email:             "jodok.troesch@unibas.ch"
#  twitter:           "paululele"
#  instagram:         "paululele"
  github:            "not-balb"
  facebook:          "jodok.troesch"
#  linkedin:          "lenpaul"
navigation:
- title: Projekt
  url: /about
- title: News
  url: /writing
- title: Mitarbeitende
  url: /team
- title: Kontakt
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
