# Site Settings

title:               Theorie der Prosa
tagline:             Uni Basel
description:
baseurl:            "/Lagrange"
url:                "localhost:4000"
github:
  url:               #"https://not-balb.github.io/Lagrange"
author:
  name:              "Jodok Trösch"
  email:             "jodok.troesch@unibas.ch"
#  twitter:           "theorie-der-prosa"
#  instagram:         ""
  github:            "not-balb"
  facebook:          "jodok.troesch"
#  linkedin:          ""
navigation:
- title: Projekt
  url: /about
- title: News
  url: /writing
- title: Mitarbeitende
  url: /team
- title: Kontakt
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
